version: '3.4'

services:
  vvscide:
    build:
      context: ./vvscode/
      dockerfile: Dockerfile
      args:
        USERNAME: ${USER}
        QUARTO_VERSION: ${QUARTO_VERSION}
    user: ${USER}
    volumes:
      - ..:/workspace:cached
      - ${RENV_PATHS_CACHE_HOST}:/renv/cache
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command: sleep infinity
    # command: /bin/sh -c "while sleep 1000; do :; done"
    # links v network
    links:
      - rrstudiodevcontainer
    # ...
    env_file: .env

  rrstudiodevcontainer:
    build:
      context: ./rrstudiodevcontainer/
      dockerfile: Dockerfile
      args:
        S6_VERSION: ${S6_VERSION}
        RSTUDIO_VERSION: ${RSTUDIO_VERSION}
        QUARTO_VERSION: ${QUARTO_VERSION}
    volumes:
      - ${VOLUME_PATH}:${VOLUME_PATH}
      - /home/${USER}/.ssh:/home/${USER}/.ssh
      - ${RENV_PATHS_CACHE_HOST}:${RENV_PATHS_CACHE_CONTAINER}
      - ${VOLUME_PATH}/.devcontainer/rstudio_config_dir:/home/${USER}/.config/rstudio
    restart:
      unless-stopped
    ports:
      - ${LOCAL_PORT}:8787
    env_file: .env
    command: sleep infinity
    # command: /bin/sh -c "while sleep 1000; do :; done"
